import org.jetbrains.kotlin.gradle.dsl.JvmTarget
import java.util.Properties

plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.compose)
}

// Signing secrets live in keystore.properties (gitignored, generated by
// scripts/gen-keystore.ps1) — never committed, never logged.
val keystoreProps = Properties().apply {
    val f = rootProject.file("keystore.properties")
    if (f.exists()) f.inputStream().use { load(it) }
}

// Local secrets (e.g. the MapTiler key) live in local.properties
// (gitignored). Gradle does NOT auto-load custom keys from that file into
// project properties (only `sdk.dir`, which AGP reads itself), so read it
// explicitly — same pattern as keystore.properties above.
val localProps = Properties().apply {
    val f = rootProject.file("local.properties")
    if (f.exists()) f.inputStream().use { load(it) }
}

android {
    namespace = "com.fafoguesser.app"
    compileSdk {
        version = release(36) {
            minorApiLevel = 1
        }
    }

    defaultConfig {
        applicationId = "com.fafoguesser.app"
        minSdk = 26
        targetSdk = 36
        versionCode = 1
        versionName = "1.0"

        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"

        buildConfigField(
            "String",
            "SERVER_URL",
            "\"${project.findProperty("fafo.serverUrl") ?: "http://10.0.2.2:8787"}\"",
        )
        buildConfigField(
            "String",
            "MAPTILER_API_KEY",
            "\"${localProps.getProperty("fafo.maptilerKey") ?: ""}\"",
        )
    }

    signingConfigs {
        if (keystoreProps["storeFile"] != null) {
            create("release") {
                storeFile = rootProject.file(keystoreProps["storeFile"] as String)
                storePassword = keystoreProps["storePassword"] as String
                keyAlias = keystoreProps["keyAlias"] as String
                keyPassword = keystoreProps["keyPassword"] as String
            }
        }
    }

    buildTypes {
        release {
            // R8 minify+optimize (C3): shrinks the APK and makes the
            // business logic far harder to recover from a pulled-apart APK.
            // pano.html's bridge class survives via keepRules/rules.keep.
            optimization {
                enable = true
            }
            signingConfig = signingConfigs.findByName("release")
            // Debug defaults to the emulator host; release must never ship
            // that. Override per build with -Pfafo.serverUrlRelease=...
            buildConfigField(
                "String",
                "SERVER_URL",
                "\"${project.findProperty("fafo.serverUrlRelease") ?: "https://fafoserver.onrender.com"}\"",
            )
        }
    }

    buildFeatures {
        compose = true
        buildConfig = true
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_11
        targetCompatibility = JavaVersion.VERSION_11
    }
}

kotlin {
    compilerOptions {
        jvmTarget = JvmTarget.JVM_11
    }
}

dependencies {
    implementation(libs.androidx.core.ktx)
    implementation(libs.androidx.activity.compose)
    implementation(libs.androidx.lifecycle.runtime.compose)
    implementation(libs.androidx.lifecycle.viewmodel.compose)
    implementation(platform(libs.androidx.compose.bom))
    implementation(libs.androidx.compose.ui)
    implementation(libs.androidx.compose.ui.tooling.preview)
    implementation(libs.androidx.compose.material3)
    implementation(libs.socket.io.client)
    implementation(libs.maptiler.sdk)
    debugImplementation(libs.androidx.compose.ui.tooling)

    testImplementation(libs.junit)
    androidTestImplementation(libs.androidx.espresso.core)
    androidTestImplementation(libs.androidx.junit)
}
